version: "3"

services:
  server1:
    build:
      context: server1
    volumes:
      - ./static:/static
  server2:
    build:
      context: server2
    volumes:
      - ./static:/static
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "10000:80"
    depends_on:
      - server1
      - server2
